# Generated by Django 4.2.11 on 2024-04-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='journey.place'),
        ),
    ]
