# Generated by Django 4.2.11 on 2024-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_imageplace_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(default='Краткое описание', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
