# Generated by Django 4.2.11 on 2024-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_place_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='market_label',
            field=models.CharField(default='mid', max_length=100, verbose_name='Маркет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(db_index=True, default='pid', max_length=100, verbose_name='ID места'),
            preserve_default=False,
        ),
    ]
