# Generated by Django 4.2.11 on 2024-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_place_market_label_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageplace',
            options={'ordering': ['position'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения мест'},
        ),
        migrations.AddField(
            model_name='imageplace',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
