# Generated by Django 4.2.11 on 2024-04-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_imageplace_options_imageplace_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageplace',
            unique_together={('place', 'position')},
        ),
    ]
