# Generated by Django 4.2.11 on 2024-04-22 16:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_alter_imageplace_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
