# Generated by Django 4.2.11 on 2024-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0009_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='imageplace',
            name='title',
        ),
        migrations.AlterField(
            model_name='imageplace',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='market_label',
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
