# Generated by Django 4.2.11 on 2024-04-24 22:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0010_alter_place_unique_together_remove_imageplace_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journey.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
