# Generated by Django 4.2.11 on 2024-04-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0011_alter_imageplace_place_alter_place_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
