# Generated by Django 4.2.11 on 2024-04-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0012_rename_description_place_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
