# Generated by Django 4.2.11 on 2024-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0013_remove_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
