# Generated by Django 4.2.11 on 2024-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0014_alter_imageplace_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title',)},
        ),
    ]
